### ISSUE TITLE
v0.3 seems to be incompatible with D 2.091.1

### ISSUE THREAD

**Issue by 0xEAB** [rejectedsoftware/userman#29]
```d
../../.dub/packages/vibe-d-0.8.6/vibe-d/web/vibe/web/web.d(197,6): Error: static assert:  "Instances may only be returned from parameter-less functions (__ctor)!"
source/userman/web.d(34,29):        instantiated from here: registerWebInterface!(UserManWebInterface, cast(MethodStyle)5)
```

- https://github.com/rejectedsoftware/userman/blob/0.3/source/userman/web.d#L34
- https://github.com/vibe-d/vibe.d/blob/v0.8.6/web/vibe/web/web.d#L197

I wonder whether this is caused by a regression or expected (new) behavior?

**Comment by Geod24** [comment]
I think we can close this ?

**Comment by 0xEAB** [comment]
indeed, compiles fine here (LDC 1.30.0 (DMD v2.100.1, LLVM 14.0.3)).
